name = 'apodimagery'
main = "src/index.ts"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]


# AI binding for machine learning models
[ai]
binding = "AI"

# D1 Database binding for metadata storage
[[d1_databases]]
binding = "APOD_D1"
database_name = "apod-metadata-dev"
database_id = "115747db-5068-480e-b940-535053fd1df7"
migrations_dir = "src/migrations"

# R2 Storage binding for image files
[[r2_buckets]]
binding = "APOD_R2"
bucket_name = "apod-images-dev"

[[vectorize]]
binding = "APOD_BASE_768D_VECTORIZE"
index_name = "apod_base_768d"

[[vectorize]]
binding = "APOD_IMAGE_EMBEDDINGS_VECTORIZE"
index_name = "apod_img_embeddings"

# Environment variables
[vars]
NASA_API_KEY = "2Z2f8SV5T9lqulgJmTdagO5gQkoOzZKkiQeHfoII"
MAX_CONCURRENT_PROCESSING = "5"
BATCH_SIZE = "10"
RETRY_ATTEMPTS = "3"
ENABLE_DETAILED_LOGGING = "false"

# Production environment overrides
[env.production]
[env.production.vars]
MAX_CONCURRENT_PROCESSING = "10"
BATCH_SIZE = "20"
ENABLE_DETAILED_LOGGING = "false"

# Development environment overrides
[env.development]
[env.development.vars]
d1_databases = { binding = "APOD_D1", database_name = "apod-metadata-dev"}
r2_buckets = { binding = "APOD_R2", bucket_name = "apod-images-dev" }
vectorize = { binding = "VECTORIZE_INDEX", index_name = "apod-embeddings-dev" }

[observability.logs]
enabled = true
