const mockApodData = [
  {
    date: "1995-06-16",
    title: "Neutron Star Earth",
    explanation: "If the Earth could somehow be transformed to the ultra-high density of a neutron star...",
    url: "https://apod.nasa.gov/apod/image/e_lens.gif",
    hdurl: "https://apod.nasa.gov/apod/image/e_lens.gif",
    media_type: "image",
    copyright: "nan",
    predicted_category: "Earth/Atmospheric",
    confidence_score: 0.050452280789613724,
  },
  {
    date: "1995-06-17",
    title: "Another Celestial Event",
    explanation: "A brief description of another celestial event on this date.",
    url: "https://apod.nasa.gov/apod/image/9506/m100_hst.gif",
    hdurl: "https://apod.nasa.gov/apod/image/9506/m100_hst.gif",
    media_type: "image",
    copyright: "nan",
    predicted_category: "Star Cluster",
    confidence_score: 0.06,
  },
  {
    date: "1995-06-18",
    title: "Comet Approaching",
    explanation: "Details about a comet's trajectory and appearance.",
    url: "https://apod.nasa.gov/apod/image/9506/comet_halebopp.gif",
    hdurl: "https://apod.nasa.gov/apod/image/9506/comet_halebopp.gif",
    media_type: "image",
    copyright: "nan",
    predicted_category: "Comet",
    confidence_score: 0.07,
  },
  {
    date: "1995-06-19",
    title: "Distant Galaxy",
    explanation: "An image of a galaxy far, far away.",
    url: "https://apod.nasa.gov/apod/image/9506/m31_hst.gif",
    hdurl: "https://apod.nasa.gov/apod/image/9506/m31_hst.gif",
    media_type: "image",
    copyright: "nan",
    predicted_category: "Galaxy",
    confidence_score: 0.08,
  },
  {
    date: "1995-06-20",
    title: "Pleiades Star Cluster",
    explanation: "The Pleiades star cluster, M45, is one of the brightest star clusters visible in the northern hemisphere.",
    url: "https://apod.nasa.gov/apod/image/pleiades2.gif",
    hdurl: "https://apod.nasa.gov/apod/image/pleiades2.gif",
    media_type: "image",
    copyright: "nan",
    predicted_category: "Star Cluster",
    confidence_score: 0.06748884916305542,
  },
];

export default mockApodData;
