name = "api-gateway"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
# Add any environment variables here if needed

[[r2_buckets]]
binding = "APOD_DATA" # This is the variable name you'll use in your Worker code
bucket_name = "APOD_DATA_BUCKET" # This is the actual name of your R2 bucket
